// <auto-generated/>
#nullable enable

using Exanite.Engine.ResourceManagement;
using Exanite.ResourceManagement;

namespace Exanite.Engine.Consumer;

/// <summary>
/// Automatically generated resources definitions
/// based on the files contained in this project's Content folder
/// and the Content folders of this project's dependencies.
/// This generation occurs when the project is rebuilt.
/// </summary>
/// <remarks>
/// Changes made to this file will be lost.
/// However, you may need to manually edit this file at times
/// if it is blocking the project from being rebuilt.
/// </remarks>
[GeneratedResourceClass]
internal partial class Resources
{
    // Path: Exanite.Engine/Rendering

    public static readonly ResourceDefinition<global::Exanite.Engine.Sprites.Sprite> ExaniteEngine_Rendering_Icon_Sprite = new("/Exanite.Engine/Icon.png");

    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.Texture2D> ExaniteEngine_Rendering_Icon_Texture = new("/Exanite.Engine/Icon.png");

    // Path: Exanite.Engine/Fonts

    public static readonly ResourceDefinition<global::Exanite.Prowl.Paper.FontFile> ExaniteEngine_Fonts_FieryTurk_Font = new("/Exanite.Engine/Fonts/FieryTurk.ttf");
    public static readonly ResourceDefinition<global::Exanite.Prowl.Paper.FontFile> ExaniteEngine_Fonts_NotoSansRegular_Font = new("/Exanite.Engine/Fonts/NotoSans-Regular.ttf");

    // Path: Exanite.Engine/PostProcessing

    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_PostProcessing_BloomDown_FragmentModule = new("/Exanite.Engine/PostProcessing/BloomDown.fragment.slang");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_PostProcessing_BloomUp_FragmentModule = new("/Exanite.Engine/PostProcessing/BloomUp.fragment.slang");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_PostProcessing_ToneMap_FragmentModule = new("/Exanite.Engine/PostProcessing/ToneMap.fragment.slang");

    // Path: Exanite.Engine/Rendering

    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_Rendering_Blit_FragmentModule = new("/Exanite.Engine/Rendering/Blit.fragment.slang");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_Rendering_ScreenQuad_VertexModule = new("/Exanite.Engine/Rendering/ScreenQuad.vertex.slang");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_Rendering_ScreenTri_VertexModule = new("/Exanite.Engine/Rendering/ScreenTri.vertex.slang");

    // Path: Exanite.Engine/Sprites

    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_Sprites_Sprite_FragmentModule = new("/Exanite.Engine/Sprites/Sprite.fragment.slang");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_Sprites_Sprite_VertexModule = new("/Exanite.Engine/Sprites/Sprite.vertex.slang");

    // Path: Exanite.Engine/UserInterfaces

    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_UserInterfaces_Ui_FragmentModule = new("/Exanite.Engine/UserInterfaces/Ui.fragment.slang");
    public static readonly ResourceDefinition<global::Exanite.Engine.Graphics.ShaderModule> ExaniteEngine_UserInterfaces_Ui_VertexModule = new("/Exanite.Engine/UserInterfaces/Ui.vertex.slang");
}
